version: "3"

services:
  api:
    image: api-engine
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - .:/app
    ports:
      - "9000:9000"
      - "5858:5858"
    networks:
      - webnet
  mongodb:
    # By default Compose sets up a single network for your app. Each container for a service
    # joins the default network and is both reachable by other containers on that network,
    # and discoverable by them at a hostname identical to the container name.
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#      - MONGODB_USER="user" 
#      - MONGODB_PASS="pass"
    volumes:
      - "./data:/data"
    ports:
      - "27017:27017"
    networks:
      - webnet

networks:
  webnet:    
